import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const satoshi = localFont({ src: './Satoshi-Variable.woff2' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`overflow-x-hidden relative bg-gradient-to-br from-[#1e1e20] from-10% to-[#0e0e11] ${satoshi.className}`}
      >
        <div
          id='galaxy'
          className='bg-[url("/galaxy.png")] absolute bg-[length:1090px] bg-[50%_center] top-0 left-0 right-0 bottom-0 overflow-hidden z-[-1]'
        />
        <div className='absolute top-0 left-0 right-0 bottom-0 overflow-hidden'>
          <div className="relative -bottom-[250px] -left-[350px] mobile:-bottom-[450px] mobile:-left-[450px] bg-[url('/planet.png')] w-[800px] h-[800px] mobile:w-[1200px] mobile:h-[1200px] bg-cover bg-center animate-breathe"></div>
        </div>
        <div className='display flex justify-center desktop:items-center h-full'>
          {children}
        </div>
      </body>
    </html>
  );
}
